### ISSUE TITLE
Styles are broken if hook names are not valid CSS identifiers

### ISSUE THREAD

**Issue by markdalgleish** [css-hooks/css-hooks#11]
I initially tried configuring my hooks like this because I wanted to remove any aliasing and make it feel closer to raw CSS:

```js
createHooks({
  "@media (prefers-color-scheme: dark)": "@media (prefers-color-scheme: dark)",
  "@media (min-width: 640px)": "@media (min-width: 640px)",
  "@media (min-width: 768px)": "@media (min-width: 768px)",
  "@media (min-width: 1024px)": "@media (min-width: 1024px)",
});
```

However this leads to invalid CSS:

```css
*{--@media (prefers-color-scheme: dark)-0:initial; /* etc. */ }
```

What do you think about mapping hook names to short identifiers internally so that you're free to name them whatever you want? This would also help make the generated styles a bit shorter too.

**Comment by nsaunders** [comment]
Thanks for the report @markdalgleish. I think this could be tackled in two phases:

1. Quick fix: Update the type definition for the `createHooks` function to prevent this (currently) invalid configuration.
2. Review and implement the internal mapping you described.

Regarding the second point, the main trade-off that comes to mind is that a little bit of "readability" would be lost in the generated style sheet and `style` attribute value. For me, that's not much of a problem, but it's just something that might pop up in another issue later.

**Comment by robinweser** [comment]
Just stumbled over this repo and have to say this is exactly what I was looking for!
FWIW I'd also like to author my styles without aliases if possible. Less magic and more familiar I'd assume.
