### ISSUE TITLE
Feature idea: Support custom prefix for scoping of variable names

### ISSUE THREAD

**Issue by markdalgleish** [css-hooks/css-hooks#12]
It'd be nice to be able to pass in a custom prefix so that all variable names can be scoped, particularly when building design systems and component libraries.

**Comment by nsaunders** [comment]
Yes, this has occurred to me as well, so we must be on to something.

Considering #11 also, what would you think about the idea of simply hashing the content of the "hook spec" to determine the underlying variable name? It seems to me that this would mitigate any scoping concerns while also producing a valid CSS identifier.

**Comment by markdalgleish** [comment]
Hashing the hook spec is a nice way to avoid adding a specific API for scoping, especially since the hash only needs to be generated once. I like that idea.
