### ISSUE TITLE
Feature Request: Fallback Values

### ISSUE THREAD

**Issue by robinweser** [css-hooks/css-hooks#14]
I was just trying to see if I could get [Fela plugins](https://fela.js.org/docs/latest/intro/ecosystem#plugins) to work with CSS hooks to enable my usual workflow including vendor prefixing and everything.
In theory it should work for most simple plugins as their signature is identical, but I ran into issues with vendor prefixing itself.
For example, some properties require multiple different values.
```css
display: -webkit-box;
display: -moz-box;
display: -ms-flexbox;
display: -webkit-flex;
display: flex
```

To replicate that with default inline styles, we can do the following:
```js
const style = {
  display: "-webkit-box;display:-moz-box;display:-ms-flexbox;display:-webkit-flex;display:flex"
}
```

With hooks the display prop gets removed from the style object though. I'm traveling right now, so not the best setup to dive into the codebase myself, but happy to help or discuss it further!
If we could get this to work, you could get stuff like vendor prefixing using Fela plugins directly.

**Comment by nsaunders** [comment]
Wow, that sounds great! I'm not available to dive in right away, but I will definitely look into this.

In the meantime, I would imagine that we can start exploring this without actually making changes to the library right away. Remember, you basically create your own `hooks` function anyway, so it should be possible to create a wrapper that provides additional functionality.

**Comment by robinweser** [comment]
Yeah! Already played with that and works fine for most thing actually. Just the multi-value strings don‘t end up in the actual output for some reason.
Might dig deeper once I‘m back this weekend ☺️

**Comment by robinweser** [comment]
Ok nvm. After some research, I found the answer - written 7 years ago by myself 😂 
https://github.com/robinweser/inline-style-prefixer/issues/78

Inline styles in React do not support fallback values, so vendor prefixing is impossible at the moment. I wonder how many prefixes one even needs nowadays though. Might do some research there as well!

**Comment by robinweser** [comment]
I'll soon be coming back to this topic, but I found a solution that works well, especially for vendor prefixing.
