### ISSUE TITLE
Question: can hooks target data attributes?

### ISSUE THREAD

**Issue by emadabdulrahim** [css-hooks/css-hooks#15]
Is it possible to style element variants using data attributes and then target those via the hooks?

If the answer is no, what's the recommended way to style variants using hooks?

**Comment by nsaunders** [comment]
Absolutely! Does [this example](https://github.com/nsaunders/nsaunders.dev/blob/ae32743bcd429bcda22da13022adea9b942c0179/src/css-hooks.ts#L12) help? Let me know if not...

**Comment by nsaunders** [comment]
One thing to note is that, if you were to do this frequently with a lot of different components, you'd bloat the hooks style sheet a bit... To me, it's perfectly fine to have some pure prop-driven styling logic within your component.

**Comment by emadabdulrahim** [comment]
Is there a performance concern if the custom hooks defs get a bit large?

**Comment by nsaunders** [comment]
Please keep the questions coming!
