### ISSUE TITLE
Default style properties getting reset if not specified in the hooks

### ISSUE THREAD

**Issue by mryechkin** [css-hooks/css-hooks#21]
Hey there! First off, absolutely love what you're doing with this library 👏  It's a breath of fresh air and very exciting. I'm a big fan.

One thing I've noticed as I started experimenting. Say I have a `button` and it has some default styles applied:

```css
/* index.css */
button {
  font-size: 1.25rem;
}
```

And my hooks definition looks like this:

```js
// css-hooks.ts
const [css, hooks] = createHooks({
  ...recommended,
  "@media (min-width: 1024px)": "@media (min-width: 1024px)",
});
```

When I specify an override for `font-size` for a specific hook, but **don't** include it in the base style overrides, ie:

```jsx
// App.tsx
<button
  style={hooks({
    background: "aquamarine",
    "@media (min-width: 1024px)": {
      background: "chartreuse",
      fontSize: "2rem",
    },
  })}
>
```

That property gets reset to browser defaults - **not** the default styles, as I was expecting.

I'm guessing this happens because of `unset`?

![Screenshot 2023-12-01 at 12 13 19 PM](https://github.com/css-hooks/css-hooks/assets/5657181/9b502510-f4a3-4930-8a7d-06a0bde0ca23)

![Screenshot 2023-12-01 at 12 14 37 PM](https://github.com/css-hooks/css-hooks/assets/5657181/e4cddc67-68ee-4ab5-b6a2-fb9ac2f393d8)

Is there any way around this? I'm looking to augment a React component library with this, where we have a very kludgy custom prop for specifying overrides. Doing it via `style` prop with the hooks would be a greatly improved experience, but the benefits would certainly be tainted if users had to specify _all_ style property overrides now, as opposed to just the ones they want.

Would love to hear your thoughts on this, and again thank you for your great work.

Here's a sandbox for reference: https://codesandbox.io/p/sandbox/vigorous-black-dkhzlv

**Comment by nsaunders** [comment]
Great question! Indeed, `unset` is the problem here, but I think that's the best fallback value available today. I believe [`revert-layer`](https://developer.mozilla.org/en-US/docs/Web/CSS/revert-layer) actually has the behavior we're looking for, but it's [not widely supported yet](https://caniuse.com/?search=revert-layer). (That said, I just did a quick test in desktop Chrome, Safari, and Firefox, and it seems there is some kind of partial support at least.)

If you're OK with the experimental status of `revert-layer`, you could do this today:

```jsx
// App.tsx
<button
  style={hooks({
    background: "aquamarine",
    fontSize: "revert-layer", // explicitly fall back to revert-layer
    "@media (min-width: 1024px)": {
      background: "chartreuse",
      fontSize: "2rem",
    },
  })}
>
```

**Comment by nsaunders** [comment]
Another solution that doesn't depend on `revert-layer` would be to introduce a custom property in the CSS file that defines the default font size:

```css
button {
  --button-default-font-size: 1.25rem;
  font-size: var(--button-default-font-size);
}
```

Then, as before, provide an explicit fallback value:

```jsx
// App.tsx
<button
  style={hooks({
    background: "aquamarine",
    fontSize: "var(--button-default-font-size)",
    "@media (min-width: 1024px)": {
      background: "chartreuse",
      fontSize: "2rem",
    },
  })}
>
```

Of course, you'll know better than I do whether this provides any benefit over your current state of affairs...

**Comment by mryechkin** [comment]
I see - thanks for confirming! Yeah, looks like `revert-layer` is doing exactly what I'm looking for here.

The problem I have with either approach though is that users would still need to specify that fallback manually, which can get pretty verbose, and is leaking implementation details IMO. But I understand the need. Will have to think about how to tackle this.

Curious, would it be possible to customize what the default fallback value is? Say instead of `unset` specifying to use `revert-layer`, that way the default behaviour would do what I'm after, without users having to pass `fontSize: "revert-layer"` manually.

Something like this?

```js
const [css, hooks] = createHooks({
  ...recommended,
  "@media (min-width: 1024px)": "@media (min-width: 1024px)",
}, {
  fallback: "revert-layer"
});
```

**Comment by nsaunders** [comment]
I love that idea! If you have any interest in contributing, I think it would be a relatively straightforward change: Just search for the two instances of `"unset"` [here](https://github.com/css-hooks/css-hooks/blob/master/packages/core/src/index.ts) and you'll see where the new option would need to be applied. On the other hand, if you're too busy, no worries at all. I'll have a go at it later this afternoon if I don't hear back from you by then.

**Comment by mryechkin** [comment]
Oh - fantastic! Happy to hear that. Thank you - I would love to, but won't have time for it this week unfortunately. This isn't a pressing matter, so please don't feel like you have to if there are other priorities - I'd be glad to look at it next week. But I'm happy to hear that a workaround is possible 🙌

**Comment by joakimbeng** [comment]
I'm curious, your blog post mentions `initial` instead of `unset`, what made you switch? Wouldn't `inherit` solve the issue the same way as `revert-layer` does? But I'm probably missing something 😄
Great library by the way! Will definitely use it!

**Comment by nsaunders** [comment]
Hi @joakimbeng, thanks for your interest and the great question.

First of all, this may be a different context than what you have in mind. The `initial` value as referenced in my blog post is the basis for the fallback trick that makes this all possible. If you're interested in reading more about that, you can find the relevant CSS spec [here](https://www.w3.org/TR/css-variables/#guaranteed-invalid).

This issue, on the other hand, is related to the "syntactic sugar" of nested style objects. Consider this example:

```javascript
{
  color: "blue",
  hover: {
    color: "lightblue"
  }
}
```

When you apply the `css` function, the resulting style object will look something like this:

```javascript
{
  color: "var(--hover-1, lightblue) var(--hover-0, blue)"
}
```

That's a fairly straightforward transformation, but what about this case?

```javascript
{
  hover: {
    color: "lightblue"
  }
}
```

Notice that there's no default `color` value. What can we use for the `--hover-0` fallback value, then?

As you mentioned, we currently use [`unset`](https://developer.mozilla.org/en-US/docs/Web/CSS/unset) in a case like this:

```javascript
{
  hover: "var(--hover-1, lightblue) var(--hover-0, unset)"
}
```

The `unset` keyword doesn't provide exactly the behavior we are probably looking for, hence the discussion of using [`revert-layer`](https://developer.mozilla.org/en-US/docs/Web/CSS/revert-layer) instead. `revert-layer` would fall back to another user-defined ruleset, like one written in a style sheet.

Unfortunately, `revert-layer` is experimental.

Hope this helps, and please let me know if it leaves you with any unanswered questions.

By the way @mryechkin, apologies for taking longer than anticipated. It is still on my radar.

**Comment by cly** [comment]
Sorry for reviving an old thread and happy to create a new one if needed.

I recently ran into this issue and I wonder if an alternative solution is to look at the css property being styled and using the default value for it instead of relying on 'unset' (not safe in safari) or 'revert-layer' (poor support).

So for `font-family` it could use `inherit` or something.

**Comment by nsaunders** [comment]
Hi @cly, thanks for reaching out with your concerns.

First, I have a couple of questions for you:
1. Can you tell me more about `unset` being unsafe in Safari?
2. Do you have any findings or resources you can share regarding `revert-layer`? I had compatibility concerns as well, but [Web Platform Tests](https://wpt.fyi/results/css/css-cascade?label=master&label=stable&product=chrome-99.0.4844.84&product=edge-99.0.1150.55&product=firefox-97.0.2&product=safari-16.4%20%2818615.1.26.110.1%29&q=revert-layer) data seems to indicate pretty wide support.

I would consider adding support for property-specific fallback values, although (to keep the library small), you'd probably need to bring your own logic via configuration, e.g.

```typescript
const { styleSheet, css } = createHooks({
  hooks: {
    // ...hook config...
  },
  fallback: propertyName => propertyName === "font-family" ? "inherit" : "revert-layer",
});
```

There was also #59 which might be similar enough that a single generic feature could be added to address both use cases...

**Comment by nsaunders** [comment]
Reopened by mistake - a bit prematurely, I think. Let's figure out how to proceed once we have a bit more information.

**Comment by cly** [comment]
1. Regarding `safari`, I thought it was the same issue as OP but actually I just tested it again and maybe it's different.

Relevant css hook:

```
light: {
    or: [
      "[data-theme='light'] &",
      {
        and: ["[data-theme='auto'] &", "@media (prefers-color-scheme: light)"],
      },
    ],
  },
  dark: {
    or: [
      "[data-theme='dark'] &",
      {
        and: ["[data-theme='auto'] &", "@media (prefers-color-scheme: dark)"],
      },
    ],
  },
  ```
  
  Relevant css():
  ```
  {
    light: {
      backgroundColor: surface.backgroundColor.hex(),
      color: surface.color.hex(),
    },
    dark: {
      backgroundColor: surface.dark.backgroundColor.hex(),
      color: surface.dark.color.hex(),
    },
  }
  ```
  
  Generates the following css rule
  ```
  var(--mbscpo-1, var(--jyjjxp-1, #393939) var(--jyjjxp-0, #ebebeb)) var(--mbscpo-0, var(--jyjjxp-1, #262626) var(--jyjjxp-0, var(--jkmqlp-1, #f5f5f5) var(--jkmqlp-0, unset)))
  ```
  
 which works in Chrome but not in safari.
 
 2. For `revert-layer` i was looking at https://caniuse.com/mdn-css_types_global_keywords_revert-layer with 3% coverage.
 
 WRT fallbacks, that seems reasonable. Although if `revert-layer` has wide support, could just use that.

**Comment by nsaunders** [comment]
@cly I'm a bit surprised by the Safari issue. The dark mode toggle on the CSS Hooks website is very similar and works fine for me in Safari. What version are you using? If you could please reproduce this in a CodeSandbox environment or similar, I'd be happy to have a look.

**Comment by cly** [comment]
Here you go: https://github.com/cly/css-hooks-playground

Actually, it behaves differently (2nd test doesn't seem to work in this repo) than what I have in another repo and I haven't figured it out yet.

Safari (16.1)
![image](https://github.com/css-hooks/css-hooks/assets/314215/a327974a-76c6-47a4-abbe-4a19c27d908e)

Chrome
![image](https://github.com/css-hooks/css-hooks/assets/314215/f672dd11-5ff8-4579-9597-7720bd0840b6)

**Comment by cly** [comment]
Actually removing the "and" block seems to work so maybe it's just a bug with the 1.8x way of create the hooks. I haven't tried it on 2.x yet.
