### ISSUE TITLE
"How it works" guide

### ISSUE THREAD

**Issue by nsaunders** [css-hooks/css-hooks#26]
I've encountered a lot of questions about how this works; and, while I've written a cheesy blog post about it, the website should really have a brief guide that introduces the underlying variable fallback trick without editorial fluff. If anyone is interested in taking this on, I'd be happy to provide a personal walkthrough if needed.

**Comment by asilvadesigns** [comment]
@nsaunders do you mind sharing the blog post in this issue? I'm certainly interested, though I can't make any promises atm

**Comment by nsaunders** [comment]
Thanks for your interest @asilvadesigns!

The blog post I referenced is [here](https://nsaunders.dev/posts/css-madness-to-hooks#the-fallback-trick), and [this spec](https://www.w3.org/TR/css-variables/#guaranteed-invalid) is also a good reference.

The [tests](https://github.com/css-hooks/css-hooks/blob/master/packages/core/__tests__/index.ts) might also help to understand how the object syntax is transformed into string values, if you haven't had a chance to dive into that yet.

If you do decide to take this on, please let me know if you need any more support in addition to the above links.

Thanks again for considering this!

**Comment by nsaunders** [comment]
@markdalgleish has a nice [demo](https://x.com/markdalgleish/status/1730777615450214652?s=20) on Twitter. Probably good to try to replicate that, in text form of course.

**Comment by nsaunders** [comment]
Resolved in [e68927d](https://github.com/css-hooks/css-hooks/commit/e68927d661729a7bb8a47da9184dfbaa1ce7519e)
