### ISSUE TITLE
Drop pseudo-class hook type

### ISSUE THREAD

**Issue by nsaunders** [css-hooks/css-hooks#53]
The [pseudo-class hook type](https://github.com/css-hooks/css-hooks/blob/3df3a44e52de7ad5ad77f68715bb3325873886c3/packages/core/src/index.ts#L11) doesn't actually seem that useful to me. Consider a hover hook:

```javascript
createHooks({
  hover: ":hover",
})
```

If you didn't have the pseudo-class hook type, you'd just use the selector type instead, the difference just being a single character:

```javascript
createHooks({
  hover: "&:hover",
})
```

And, of course, if you're using the `recommended` config API, it doesn't matter anyway:

```javascript
createHooks(recommended({
  pseudoClasses: [":hover"] // produces a `&:hover` hook
}))
```

Any thoughts on dropping this hook type in v2? Do you have a use case I should consider?

**Comment by b3nten** [comment]
the main use case is being able to write `hover` and not need to escape the object key in a string.
as long as that's still supported, i think it's fine to drop the hook type.

**Comment by zaydek** [comment]
I personally favor it being explicit. If I see `hover: ...` I will first perceive it as CSS key value versus a selector, like `&:hover` or a media query, which I believe would always need to be quoted anyway. `&:hover` also is easier to search against without worrying about missing occurrences and is more consistent without tools like emotion and Styled Components work, I think. In any case, too much/too many shorthands I think can be considered harmful in general.

**Comment by nsaunders** [comment]
Dropped in v2
