### ISSUE TITLE
Suggestion allowing custom property names

### ISSUE THREAD

**Issue by cloudkite** [css-hooks/css-hooks#59]
Would be nice to be able to define some custom shorthands for property names

for example

```
let [hooks, css] = createHooks(
  {
    ":hover": "&:hover",
  },
  {
    utils: {
      pad: val => ({ padding: val }),
      padX: val => ({ paddingLeft: val, paddingRight: val }),
      size: val => ({ width: val, height: val }),
    },
  },
);
```

I guess this could be implemented in userland by wrapping the css function, however seems like it would be more efficient if it was part of the library since I'm guessing you iterate over the properties already?

Prior art https://stitches.dev/docs/utils and in a way tailwind

**Comment by atomiks** [comment]
Agree this would be nice to see.

FWIW, `padX` can be replicated with the new native CSS logical properties `paddingInline` (`padX` for most layouts) and `paddingBlock` (`padY`).

**Comment by cloudkite** [comment]
Could also help with "Mixing shorthand and longhand properties in style objects is problematic"

Since if you allowed also overriding built in properties you could define:

```
// in createHooks config
padding: (val: number) => ({ paddingLeft: val, paddingRight: val, paddingTop: val, paddingBottom: val })

// in my component
css({ padding: 10, paddingLeft: 20 })

// would output
style = { paddingLeft: 20, paddingRight: 10, paddingTop: 10, paddingBottom: 10 }
```

Then I can more easily avoid mixing shorthand and longhand properties. Of course user would still need to define this. 
But opens door for other people or css-hooks publishing presets ie recommend utils or a tailwind-like utils

**Comment by cloudkite** [comment]
In addition would address https://github.com/css-hooks/css-hooks/issues/35

```
// in createHooks config
color: (val: "green-100" | "green-200" | etc.. ) => ({ color: resolveColor(val) })

// in a component could pickup types from config so this would autocomplete
css({ color: "green-100" })
```

again would open door for community to publish tailwind presets etc

**Comment by nsaunders** [comment]
Thanks for the suggestion! I'll look into this.

**Comment by robinweser** [comment]
@cloudkite feel free to check out https://github.com/robinweser/brandeur which builds on top of css-hooks and allows for custom plugins. It [supports](https://github.com/robinweser/brandeur#plugins) all kinds of Fela plugins including https://github.com/robinweser/fela/tree/master/packages/fela-plugin-custom-property which does exactly what you're looking for.

I'm not sure if the core library should really include these opinionated options.
