### ISSUE TITLE
Breakpoints set with `recommended` don't type hint

### ISSUE THREAD

**Issue by brandonpittman** [css-hooks/css-hooks#66]
Here's my `css.ts` file:

```ts
import { createHooks } from "@css-hooks/qwik";
import { recommended } from "@css-hooks/recommended";

export const [hooks, css] = createHooks(
  recommended({
    breakpoints: ["500px", "1000px"],
    colorSchemes: ["dark", "light"],
    pseudoClasses: [":hover", ":focus", ":active", ":disabled"],
  })
);
```

Here's my example button.
```tsx
        <button
          style={css({
            color: "red",
            "@media (width < 500px)": {
              color: "blue",
            },
            "&:disabled": {
              color: "gray",
            },
            "&:hover": {
              color: "green",
            },
          })}
        >
          styled button
        </button>
```

Here's the editor output:

<img width="1063" alt="image" src="https://github.com/css-hooks/css-hooks/assets/967145/bf7bb48a-798c-487a-9035-bcb68876de51">

The only media queries that seem to exist are the colorscheme ones but I tested it code and the media query works. 🤷🏻‍♂️  It's just the types that seem to be broken.

**Comment by nsaunders** [comment]
Hi @brandonpittman, would you please confirm the version of TypeScript you're using? For reference, v5.3 is required for the `recommended` function to work properly.

**Comment by brandonpittman** [comment]
@nsaunders 

I'm on 5.3.3 and still only see the prefers-color-scheme media queries as type hints.

**Comment by nsaunders** [comment]
@brandonpittman thanks for the update. Glad you got it sorted! Don't be sorry - this happens to me all the time.
